---
title: "HW6"
author: "Aparajita Pranjal"
date: 2023-04-24
format: pdf
editor: visual
---

## Initial code for PDB Data

First the bio3d package was installed:

```{r}
#install.packages("bio3d")
```

Sample code to improve and transform into a function:

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

A sample dendogram plot was provided to compare protein trends:

```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```

# New Function for any PDB input

```{r}
library(bio3d)

# This function reads in 3D structures of protein kinases, trims them, and plots its B-factor for further analysis.
plot_bfactors <- function(pdb_id) {
  
  # Read in PDB structure based on ID number
  pdb <- read.pdb(pdb_id)
  
  # Trim the protein to only contain chain A 
  pdb.chainA <- trim.pdb(pdb, chain="A", elety="CA")
  
  # Extract B-factors from the chain
  pdb.b <- pdb.chainA$atom$b
  
  # Plot B-factors in a line graph for visualizing trends
  plotb3(pdb.b, sse=pdb.chainA, typ="l", ylab="B-factor", main = (pdb_id))
}

# Call function with PDB ID
plot_bfactors("4AKE")
```

Trials with different inputs:

```{r}
plot_bfactors("7YOW")
plot_bfactors("8HBH")
```
